In [4]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok = True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f : 
    f.write('NumRooms, Alley, Price\n')  # 列名
    f.write('NA,Pave,127500\n') #每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178000\n')
    f.write('NA,NA,140000\n')

In [6]:
import pandas as pd
data = pd.read_csv(data_file)
data

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178000
3       NaN    NaN  140000

In [32]:
#处理缺失数据 典型方法包括：插值 删除 
#插值
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
inputs = inputs.fillna(inputs.mean(numeric_only = True))
inputs

   NumRooms  Alley
0       3.0   Pave
1       2.0    NaN
2       4.0    NaN
3       3.0    NaN

In [33]:
#对于inputs中的类别值或离散值，将NaN视为一个类别
inputs = pd.get_dummies(inputs, dummy_na = True, dtype = int)
inputs

   NumRooms   Alley_Pave   Alley_nan
0       3.0            1           0
1       2.0            0           1
2       4.0            0           1
3       3.0            0           1

In [34]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178000, 140000]))